name: coastwatch
channels:
  - conda-forge
dependencies:
  - cartopy
  - cmocean
  - matplotlib
  - netCDF4
  - pandas
  - pyproj 
  - requests
  - shapely
  - statsmodels
  - xarray
  - numpy
  - seaborn
  - scikit-learn
  - geopandas
  - regionmask
  - erddapy
  - pymannkendall
  - pyresample
  - rioxarray
  - rasterio
  - ecmwflibs
# QGIS
  - qgis
