name: coastwatch
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - cmocean
  - matplotlib
  - netCDF4
  - pandas
  - pyproj 
  - requests
  - shapely
  - statsmodels
  - xarray
  - numpy
  - requests
  - seaborn
  - scikit-learn
  - geopandas
  - regionmask
  - erddapy
  - pymannkendall
  - pyresample
  - rioxarray
  - rasterio
  - ecmwflibs
  - gh-scoped-creds
# Ensure that updating the conda env doesn't get rid of Desktop
  - qgis
  - pip
  - pip:
    # Access linux desktop from inside JupyterHub
    - jupyter-desktop-server==0.1.3
