name: py-rocket-base

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python~=3.11.0
  # gh-scoped-creds allows users to securely push to GitHub from their repo.
  # https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f has
  # some more information
  - gh-scoped-creds==4.1
  # More git tools from github-cli
  - gh~=2.32.1

  # R/RStudio Support
  - jupyter-rsession-proxy
  
  # VS Code support
  - jupyter-vscode-proxy~=0.5
  - code-server~=4.23

  # JupyterBook Addons
  - sphinx~=7.3
  - sphinxcontrib-bibtex

  # Resolves warning "No ICDs were found": https://github.com/CryoInTheCloud/hub-image/issues/50
  - ocl-icd-system
  # needed for Linux desktop to work
  - websockify>=0.10
  # Includes new subcommands (`switch` & `restore`) and vulnerability fixes
  # over the version available via ubuntu sources
  - git>=2.39

  # Desktop server
  # Not all packages will be available from conda-forge, we install from pip when we need to.
  - pip~=23.3.2
  - pip:
    # Access linux desktop from inside JupyterHub
    - jupyter-desktop-server==0.1.3
