name: Docker Image Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - 'draft_images/py-rocket-2/**'
      - 'draft_images/coastwatch-qgis/**'
      - 'draft_images/test/**'

env:
  WATCHED_DIRECTORIES: |
    draft_images/py-rocket-2
    draft_images/coastwatch-qgis
    draft_images/test

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Find changed directories
        id: find-changes
        run: |
          watched_dirs=$(echo "${WATCHED_DIRECTORIES}" | tr '\n' '|')
          watched_dirs="${watched_dirs%|}"
          
          dirs=$(git diff --name-only HEAD^ HEAD | grep -E "^(${watched_dirs})" | sed 's|/[^/]*$||' | sort -u)
          
          if [ -z "$dirs" ]; then
            echo "No changed directories"
            exit 1
          fi
          
          # Convert to JSON array for matrix strategy
          echo "::set-output name=matrix_dirs::$(echo "$dirs" | jq -R -s -c 'split("\n") | map(select(. != ""))')"

  # Build job using matrix
  build:
    runs-on: ubuntu-latest
    needs: find-changes
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-changes.outputs.matrix_dirs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use reusable action for each directory
        uses: nmfs-opensci/container-images@main
        with:
          image_dir: ${{ matrix.dir }}
          image_name: ${{ matrix.dir | split('/')[-1] }}

