name: Build and Push Docker Image
on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      image_tag:
        required: false
        type: string
        default: 'latest'
      image_dir:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Name and Directory
        id: setup
        run: |
          # Default image name to repository name if not provided
          if [ -z "${{ inputs.image_name }}" ]; then
            echo "name=${{ github.event.repository.name }}" >> $GITHUB_ENV
          else
            echo "name=${{ inputs.image_name }}" >> $GITHUB_ENV
          fi

          # Default image directory to current directory if not provided
          if [ -z "${{ inputs.image_dir }}" ]; then
            echo "dir=." >> $GITHUB_ENV
          else
            echo "dir=${{ inputs.image_dir }}" >> $GITHUB_ENV
          fi

      - name: Build the Docker image
        run: |
          docker build ${{ env.dir }} \
            -f ${{ env.dir }}/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/${{ env.name }}:${{ inputs.image_tag }} \
            --tag ghcr.io/${{ github.repository_owner }}/${{ env.name }}:latest

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.name }}:${{ inputs.image_tag }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.name }}:latest
