name: Docker Image Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - 'draft_images/py-rocket-2/**'
      - 'draft_images/coastwatch-qgis/**'
      - 'draft_images/test/**'

env:
  WATCHED_DIRECTORIES: |
    draft_images/py-rocket-2
    draft_images/coastwatch-qgis
    draft_images/test

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix_dirs: ${{ steps.find-changes.outputs.matrix_dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Find changed directories
        id: find-changes
        run: |
          watched_dirs=$(echo "${WATCHED_DIRECTORIES}" | tr '\n' '|')
          watched_dirs="${watched_dirs%|}"
          
          dirs=$(git diff --name-only HEAD^ HEAD | grep -E "^(${watched_dirs})" | sed 's|/[^/]*$||' | sort -u)
          
          if [ -z "$dirs" ]; then
            echo "No changed directories"
            echo "::set-output name=matrix_dirs::[]"  # Set an empty array to handle no changes
            exit 0
          fi
          
          # Convert to JSON array for matrix strategy
          matrix_dirs=$(echo "$dirs" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "::set-output name=matrix_dirs::$matrix_dirs"
          echo "Debugging: matrix_dirs output is $matrix_dirs"

